FROM node:20-alpine AS build

WORKDIR /app

COPY frontend/package.json /app/package.json

RUN corepack enable \
    && yarn install --network-timeout 120000

COPY frontend/ /app/

ENV REACT_APP_BACKEND_URL=""

RUN yarn build


FROM nginx:alpine

COPY nginx.meraaj.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
